on: 
  workflow_dispatch:
  milestone:
    types: [closed]
name: Milestone Closure
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USE_MILESTONE_TITLE: "true"
        OUTPUT_FOLDER: temp_release_notes
    - run: |
        cp  temp_release_notes/*.md releasenotes
        git config user.name Jonathan Channon
        git config user.email jonathan.channon@gmail.com
        git add .
        git commit -m "Generated Release Notes"
        git push 
